name: build

on:
  push:
  pull_request:

env:
  # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST FUTURE CHANGES
  PYTHONIOENCODING: UTF8

jobs:
  build:
    name: build and install from source
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      COSMO_FILES_SOURCE: ${{ github.workspace }}/tests/data
      COSMO_OUTPUT: ${{ github.workspace }}/tests
      COSMO_SMS_DB: ${{ github.workspace }}/tests/test.db
      COSMO_SMS_SOURCE: ${{ github.workspace }}/tests/data
      CRDS_SERVER_URL: 'https://hst-crds.stsci.edu'
      CRDS_PATH: ${{ github.workspace }}/tests/data/test_crds_cache
      DARK_PROGRAMS:
      MONITOR_CONFIG: ${{ github.workspace }}/tests/cosmoconfig_test.yaml

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.7'
          channels: http://ssb.stsci.edu/astroconda

      - name: install dependencies
        run: |
          conda install -c anaconda setuptools
          conda install stsci coverage

      - name: install from source
        run: pip install .

      - name: run tests
        run: coverage run -m pytest

      - name: run codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true
